### ISSUE TITLE
Memory requirements?

### ISSUE THREAD

**Issue by karllark** [radicamc/exoTEDRF#14]
In performing my JOSS review (https://github.com/openjournals/joss-reviews/issues/6898), I have having issues running the NIRISS notebook.  I keep running out of memory on my 64 Gb machine.  Is this expected?  What are the memory requirements for this notebook/reducing TSO data.  I'm not an exoplanet researcher so maybe this is obvious if I was, regardless might be good to document this at least.

**Comment by radicamc** [comment]
Just to clarify, you mean memory as in RAM, and not storage space correct? 
In any case, TSO data, particularly from NIRISS is large. Individual segments are often >8GB. So if its storage that you mean, then I'm not surprised that you run out after completing the notebook. 
I've never run into memory issues, though I normally (and I think this is standard practice) reduce my observations on a cluster as opposed to a laptop. What step is failing for you, and I can look into it?

**Comment by karllark** [comment]
Yes, I mean RAM.  A number of the steps are causing the kernel to crash.  I'll try the NIRSpec notebook next.  All looks good, but would be fun to get one of the notebooks to finish.  Maybe you can come up with a smaller example, that would likely be good for other users as well as myself and my "small" amount of RAM.  Hah!

**Comment by radicamc** [comment]
Yeah, I have the same issue running on my 16GB laptop, some steps will require too much memory and crash. 
Honestly, I think this is just an unavoidable facet of reducing TSO data, particularly from NIRISS which are the largest of all. 
I'll make a note in the documentation that the memory requirements of a laptop are likely not going to be enough to run the notebook (and analyze any other observations). 
I could, in theory, make a smaller dataset that could be reduced on a laptop. However, I don't think this would be worthwhile for a couple of reasons: 
First, I've tried to structure the notebooks for this package (and my related exoUPRF package) such that a user is able to reproduce the WASP-39b results that we published last year. These are the first exoplanet results from JWST, and are extremely well known in the field. As such, I believe it has a lot of pedagogical value to use this data for the tutorial. 
Second, as I mentioned above, in order to reduce any real observations, a user will most likely need to switch to a cluster. So I don't see too much value in testing out the code on your laptop with a fake dataset, then having to move to a cluster for real observations. In theory you'd need to re-run through the notebooks again to make sure everything works in the new installation. 
I'll make a note to try and reduce the memory requirements wherever possible, such that, perhaps, things can be run on a laptop. But I don't think this is super high-priority.
Thoughts?

**Comment by karllark** [comment]
All good thoughts.  I do agree that reducing the memory use would be good.  I did notice that there was a case where the pipeline step ran fine, but then creating the diagnostic image/plot seemed to crash things.  Maybe this is just too much on top of already running the pipeline.  Or maybe this is keeping the large data in memory instead of using the disk.  Regardless, I agree with your points.  

Mentioning the memory needs is a good and reasonable solution.

**Comment by radicamc** [comment]
Addressed in [c1c959e](https://github.com/radicamc/exoTEDRF/commit/c1c959e418a4958ad8a5ac07fda57285a97b70d5).
